### ISSUE TITLE
Access Mocha passed this inside the overwritten functions

### ISSUE THREAD

**Issue by mriegler** [jlipps/mo_Ocha#1]
In normal Mocha, inside any of the testing functions, this is bound to an object provided by Mocha.
`
it("asd", function() {
    this.timeout(123);
}
`

This 'this' binding is missing here. Passing it in explicitly would be good too.

**Comment by jlipps** [comment]
Thanks @mriegler. However I would no longer recommend using monocle or mo_Ocha, and instead recommend using `async/await`, as that will become standard in JS.

**Comment by mriegler** [comment]
Thanks for the reply.
