### ISSUE TITLE
afterEach is not getting executed when I use : require('mo_ocha').rewrite(); but it work when i use require('mocha') instead.

### ISSUE THREAD

**Issue by vimukt** [jlipps/mo_Ocha#2]
steps to reproduce , code : 

require('mo_ocha').rewrite();

before (function(){
    console.log('before');
} );
beforeEach (function(){
 console.log('beforeEach');   
} );
afterEach(function(){
    console.log('afterEach test is :'+this.currentTest.state);
} );

after (function(){
    console.log('after');
} );

describe("Test Suite", function() {
    it("info 1", function () {
       console.log('test 1' );
      });    
       
  it("info 2", function () {
       console.log('test 2' );
      });     

});

**Comment by vimukt** [comment]
workaround i am using now to make it work is : 
require('mo_ocha').rewrite();
afterEach = require('mocha').afterEach;

**Comment by jlipps** [comment]
This project is deprecated and shouldn't be used. Instead, mocha now ships with Promise support natively, and can be used with `async/await`.
